### ISSUE TITLE
compatability issue

### ISSUE THREAD

**Issue by rto700** [AntoninJuquel/lethal-company-lockout#1]
It dose not seam to work properly with LCLightsStartOffMod by joejoejoe. It just keep unlocked all day.

**Comment by AntoninJuquel** [comment]
> My bad. The power is off for the whole facilities with that mod enable, I thought it is just for the light cause all switch in the breaker box is closed.

You can disable the fact that the power affect the lockout in the config file

In Thunderstorm:
![image](https://github.com/AntoninJuquel/lethal-company-lockout/assets/57025128/093fbc02-8243-4264-814b-882f08be58b2)
